#ifndef LSDSLAMFRAME_GLOBAL_H
#define LSDSLAMFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LSDSLAMFRAME_LIBRARY)
#  define LSDSLAMFRAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LSDSLAMFRAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LSDSLAMFRAME_GLOBAL_H
